In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv


In [2]:
train = pd.read_csv('/kaggle/input/titanic/train.csv')
test = pd.read_csv('/kaggle/input/titanic/test.csv')
sub = pd.read_csv('/kaggle/input/titanic/gender_submission.csv')

train.shape, test.shape, sub.shape

((891, 12), (418, 11), (418, 2))

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [4]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [5]:
### 결측치 처리하기
## train - Embarked
## test - Fare

train['Embarked'].value_counts()  # 확인용
train['Embarked'] = train['Embarked'].fillna('Q')

test['Fare'] = test['Fare'].fillna(test['Fare'].mean())

train.isnull().sum(), test.isnull().sum()

(PassengerId      0
 Survived         0
 Pclass           0
 Name             0
 Sex              0
 Age            177
 SibSp            0
 Parch            0
 Ticket           0
 Fare             0
 Cabin          687
 Embarked         0
 dtype: int64,
 PassengerId      0
 Pclass           0
 Name             0
 Sex              0
 Age             86
 SibSp            0
 Parch            0
 Ticket           0
 Fare             0
 Cabin          327
 Embarked         0
 dtype: int64)

In [6]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [7]:
sel = ['Pclass', 'SibSp', 'Parch']

X_train = train[sel]
X_test = test[sel]
y_train = train['Survived']

In [8]:
from sklearn.tree import DecisionTreeClassifier

dc_tree = DecisionTreeClassifier()
dc_tree.fit(X_train, y_train)

# 예측
pred = dc_tree.predict(X_test)
pred[:15]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1])

---

In [9]:
train['Sex'] = train['Sex'].map({'female':1, 'male':0}).astype(int)
test['Sex'] = test['Sex'].map({'female':1, 'male':0}).astype(int)

train['Embarked'] = train['Embarked'].map({'S':0, 'C':1, 'Q':2}).astype(int)
test['Embarked'] = test['Embarked'].map({'S':0, 'C':1, 'Q':2}).astype(int)

In [10]:
train.info(), test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    int64  
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     891 non-null    int64  
dtypes: float64(2), int64(7), object(3)
memory usage: 83.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass  

(None, None)

In [11]:
name = []

for i in test['Name']:
    name_tmp = i.split(', ')[1]
    name_tmp = name_tmp.split(' ')[0]
    name.append(name_tmp)
    
name_ser = pd.Series(name)    
name_ser, name_ser.unique()

(0          Mr.
 1         Mrs.
 2          Mr.
 3          Mr.
 4         Mrs.
         ...   
 413        Mr.
 414      Dona.
 415        Mr.
 416        Mr.
 417    Master.
 Length: 418, dtype: object,
 array(['Mr.', 'Mrs.', 'Miss.', 'Master.', 'Ms.', 'Col.', 'Rev.', 'Dr.',
        'Dona.'], dtype=object))

In [12]:
for idx, one in enumerate(name):
    if one == 'Mr.': name[idx] = 0 
    elif one == 'Ms.' or one == 'Mrs.' or one == 'Miss.': name[idx] = 1 
    elif one == 'Master.': name[idx] = 2 
    elif one == 'Rev.': name[idx] = 3 
    elif one == 'Dr.': name[idx] = 4 
    elif one == 'Major.': name[idx] = 5 
    elif one == 'Col.': name[idx] = 6 
    else: name[idx] = 7

In [13]:
name = pd.Series(name)
test['Name_code'] = name
name.unique(), test.head(10)

(array([0, 1, 2, 6, 3, 4, 7]),
    PassengerId  Pclass                                          Name  Sex  \
 0          892       3                              Kelly, Mr. James    0   
 1          893       3              Wilkes, Mrs. James (Ellen Needs)    1   
 2          894       2                     Myles, Mr. Thomas Francis    0   
 3          895       3                              Wirz, Mr. Albert    0   
 4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   
 5          897       3                    Svensson, Mr. Johan Cervin    0   
 6          898       3                          Connolly, Miss. Kate    1   
 7          899       2                  Caldwell, Mr. Albert Francis    0   
 8          900       3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)    1   
 9          901       3                       Davies, Mr. John Samuel    0   
 
     Age  SibSp  Parch     Ticket     Fare Cabin  Embarked  Name_code  
 0  34.5      0      0     330911   7

In [14]:
name = []

for i in train['Name']:
    name_tmp = i.split(', ')[1]
    name_tmp = name_tmp.split(' ')[0]
    name.append(name_tmp)

name_ser = pd.Series(name)    
name_ser, name_ser.unique()

(0        Mr.
 1       Mrs.
 2      Miss.
 3       Mrs.
 4        Mr.
        ...  
 886     Rev.
 887    Miss.
 888    Miss.
 889      Mr.
 890      Mr.
 Length: 891, dtype: object,
 array(['Mr.', 'Mrs.', 'Miss.', 'Master.', 'Don.', 'Rev.', 'Dr.', 'Mme.',
        'Ms.', 'Major.', 'Lady.', 'Sir.', 'Mlle.', 'Col.', 'Capt.', 'the',
        'Jonkheer.'], dtype=object))

In [15]:
for idx, one in enumerate(name):
    if one == 'Mr.': name[idx] = 0 
    elif one == 'Ms.' or one == 'Mrs.' or one == 'Miss.': name[idx] = 1 
    elif one == 'Master.': name[idx] = 2 
    elif one == 'Rev.': name[idx] = 3 
    elif one == 'Dr.': name[idx] = 4 
    elif one == 'Major.': name[idx] = 5 
    elif one == 'Col.': name[idx] = 6 
    else: name[idx] = 7

In [16]:
name = pd.Series(name)
name.value_counts().head(10)

0    517
1    308
2     40
7      9
4      7
3      6
5      2
6      2
dtype: int64

In [17]:
train['Name_code'] = name
train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   
5                                   Moran, Mr. James    0   NaN      0      0   
6                            McCarthy, Mr. Timothy J    0  54.0      0      0   
7                     Palsson, Master. Gosta Leonard    0   2.0      3      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    1  27.0      0      2   
9                Nasser, Mrs. Nicholas (Adele Achem)    1  14.0      1      0   

             Ticket     Fare Cabin  Embarked  Name_code  
0         A/5 21171   7.2500   NaN         0          0  
1          PC 17599  71.2833   C85         1          1  
2  STON/O2. 3101282   7.9250   NaN         0          1  
3            113803  53.1000  C123         0          1  
4            373450   8.0500   NaN         0          0  
5            330877   8.4583   NaN         2          0  
6             17463  51.8625   E46         0          0  
7            349909  21.0750   NaN         0          2  
8            347742  11.1333   NaN         0          1  
9            237736  30.0708   NaN         1          1

In [18]:
train['Name_code'].value_counts()

0    517
1    308
2     40
7      9
4      7
3      6
5      2
6      2
Name: Name_code, dtype: int64

In [19]:
### 새로운 특징(feature(특성), variable(변수)) 만들기
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
Name_code        0
dtype: int64

In [20]:
train['Cabin'].isnull()

0       True
1      False
2       True
3      False
4       True
       ...  
886     True
887    False
888     True
889    False
890     True
Name: Cabin, Length: 891, dtype: bool

In [21]:
train['Cabin'].isnull()

0       True
1      False
2       True
3      False
4       True
       ...  
886     True
887    False
888     True
889    False
890     True
Name: Cabin, Length: 891, dtype: bool

In [22]:
train['Cabin_bool'] = ~train['Cabin'].isnull()
test['Cabin_bool'] = ~test['Cabin'].isnull()
train['Cabin_bool'] = train['Cabin_bool'].map({True:1, False:0})
test['Cabin_bool'] = test['Cabin_bool'].map({True:1, False:0})

train['Cabin_bool'].head(), test['Cabin_bool'].head()

(0    0
 1    1
 2    0
 3    1
 4    0
 Name: Cabin_bool, dtype: int64,
 0    0
 1    0
 2    0
 3    0
 4    0
 Name: Cabin_bool, dtype: int64)

In [23]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Name_code',
       'Cabin_bool'],
      dtype='object')

In [24]:
### 의사결정트리 decision tree : 0.76555

In [25]:
# pd.set_option('display.max_rows', None)

ticket = []

for i in train['Ticket']:
    temp = i.split(' ')
    if len(temp) == 2:
        ticket.append(temp[0])
    else:
        ticket.append('')
        
ticket = pd.Series(ticket)
ticket.unique()

array(['A/5', 'PC', 'STON/O2.', '', 'PP', 'A/5.', 'C.A.', 'A./5.',
       'SC/Paris', 'S.C./A.4.', 'A/4.', 'CA', 'S.P.', 'S.O.C.', 'SO/C',
       'W./C.', 'SOTON/OQ', 'W.E.P.', 'A4.', 'C', 'SOTON/O.Q.',
       'SC/PARIS', 'S.O.P.', 'A.5.', 'Fa', 'CA.', 'F.C.C.', 'W/C',
       'SW/PP', 'SCO/W', 'P/PP', 'SC', 'SC/AH', 'A/S', 'A/4', 'WE/P',
       'S.W./PP', 'S.O./P.P.', 'F.C.', 'SOTON/O2', 'S.C./PARIS',
       'C.A./SOTON'], dtype=object)

In [26]:
for idx, one in enumerate(ticket):
    if one == 'A/5' or one == 'A/5.' or one == 'A./5.' or one == 'A.5.': ticket[idx] = 1 
    elif one == 'PC': ticket[idx] = 2 
    elif one == 'C.A.' or one == 'CA' or one == 'CA.': ticket[idx] = 3 
    elif one == 'SC/Paris' or one == 'SC/PARIS' or one == 'S.C./PARIS': ticket[idx] = 4 
    elif one == 'A/4.' or one == 'A4.' or one == 'A/4': ticket[idx] = 5 
    elif one == 'W./C.' or one == 'W/C': ticket[idx] = 6 
    elif one == 'SOTON/OQ' or one == 'SOTON/O.Q.' or one == 'SOTON/O2': ticket[idx] = 7 
    elif one == 'C': ticket[idx] = 8 
    elif one == 'F.C.C.': ticket[idx] = 9 
    elif one == 'S.O./P.P.': ticket[idx] = 10 
    else: ticket[idx] = 0 

In [27]:
ticket = pd.Series(ticket)
ticket.value_counts()

0     711
2      60
3      41
1      21
7      17
4      11
6      10
5       7
8       5
9       5
10      3
dtype: int64

In [28]:
train['Ticket_code'] = ticket
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin  Embarked  Name_code  Cabin_bool  \
0         A/5 21171   7.2500   NaN         0          0           0   
1          PC 17599  71.2833   C85         1          1           1   
2  STON/O2. 3101282   7.9250   NaN         0          1           0   
3            113803  53.1000  C123         0          1           1   
4            373450   8.0500   NaN         0          0           0   

  Ticket_code  
0           1  
1           2  
2           0  
3           0  
4           0

In [29]:
pd.set_option('display.max_rows', 10)

ticket = []

for i in test['Ticket']:
    temp = i.split(' ')
    if len(temp) == 2:
        ticket.append(temp[0])
    else:
        ticket.append('')
        
ticket = pd.Series(ticket)
ticket.unique()

array(['', 'A/4', 'W.E.P.', 'SC/PARIS', 'STON/O2.', 'PC', 'C', 'A/5.',
       'SC/AH', 'C.A.', 'W./C.', 'SOTON/O.Q.', 'SC/A.3', 'F.C.C.', 'F.C.',
       'A./5.', 'PP', 'STON/OQ.', 'SOTON/OQ', 'CA', 'SC/A4', 'S.O./P.P.',
       'CA.', 'S.O.C.', 'SOTON/O2', 'AQ/4', 'SC', 'A/5', 'SC/Paris', 'LP',
       'AQ/3.', 'S.C./PARIS', 'A.5.'], dtype=object)

In [30]:
for idx, one in enumerate(ticket):
    if one == 'A/5' or one == 'A/5.' or one == 'A./5.' or one == 'A.5.': ticket[idx] = 1 
    elif one == 'PC': ticket[idx] = 2 
    elif one == 'C.A.' or one == 'CA' or one == 'CA.': ticket[idx] = 3 
    elif one == 'SC/Paris' or one == 'SC/PARIS' or one == 'S.C./PARIS': ticket[idx] = 4 
    elif one == 'A/4.' or one == 'A4.' or one == 'A/4': ticket[idx] = 5 
    elif one == 'W./C.' or one == 'W/C': ticket[idx] = 6 
    elif one == 'SOTON/OQ' or one == 'SOTON/O.Q.' or one == 'SOTON/O2': ticket[idx] = 7 
    elif one == 'C': ticket[idx] = 8 
    elif one == 'F.C.C.': ticket[idx] = 9 
    elif one == 'S.O./P.P.': ticket[idx] = 10 
    else: ticket[idx] = 0 

In [31]:
ticket = pd.Series(ticket)
test['Ticket_code'] = ticket

test['Ticket_code'].value_counts()

0     315
2      32
3      27
7      10
4       8
     ... 
6       5
9       4
10      4
5       3
8       3
Name: Ticket_code, Length: 11, dtype: int64

In [32]:
train['Family_size'] = train['SibSp'] + train['Parch'] + 1
test['Family_size'] = test['SibSp'] + test['Parch'] + 1

In [33]:
sel = ['Pclass', 'SibSp', 'Parch', 'Fare', 'Cabin_bool', 'Embarked', 'Ticket_code']

X_train = train[sel]
X_test = test[sel]
y_train = train['Survived']

In [34]:
from sklearn.tree import DecisionTreeClassifier

dc_tree = DecisionTreeClassifier()
dc_tree.fit(X_train, y_train)

# 예측
pred = dc_tree.predict(X_test)
pred[:15]

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [35]:
print(sub.columns)
sub['Survived'] = pred

sub.to_csv('decision_first_model.csv', index=False)

Index(['PassengerId', 'Survived'], dtype='object')


In [36]:
all_titanic = pd.concat([train, test], join='inner')
all_titanic.shape, all_titanic.columns

((1309, 15),
 Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
        'Ticket', 'Fare', 'Cabin', 'Embarked', 'Name_code', 'Cabin_bool',
        'Ticket_code', 'Family_size'],
       dtype='object'))

In [37]:
all_titanic['Age'] = all_titanic['Age'].fillna( all_titanic['Age'].mean()  )
all_titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 0 to 417
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  1309 non-null   int64  
 1   Pclass       1309 non-null   int64  
 2   Name         1309 non-null   object 
 3   Sex          1309 non-null   int64  
 4   Age          1309 non-null   float64
 5   SibSp        1309 non-null   int64  
 6   Parch        1309 non-null   int64  
 7   Ticket       1309 non-null   object 
 8   Fare         1309 non-null   float64
 9   Cabin        295 non-null    object 
 10  Embarked     1309 non-null   int64  
 11  Name_code    1309 non-null   int64  
 12  Cabin_bool   1309 non-null   int64  
 13  Ticket_code  1309 non-null   object 
 14  Family_size  1309 non-null   int64  
dtypes: float64(2), int64(9), object(4)
memory usage: 163.6+ KB


In [38]:
## qcut  : 전체를 동일한 사이즈로 나눠줌
all_titanic['qcut_Age'] = pd.qcut(all_titanic['Age'], 5, labels=False)   # 5 등분
all_titanic['qcut_Age'].unique()

array([1, 3, 2, 4, 0])